CREATE TABLE USER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    GENDER ENUM('MALE', 'FEMALE', 'OTHER')
);

CREATE TABLE STORE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE STORE_REVIEW (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STORE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    RATING INT NOT NULL,
    CONTENT TEXT,
    FOREIGN KEY (STORE_ID) REFERENCES STORE(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
